// === all orders ===

GET http://localhost:3000/orders


###

// === add order ===

POST http://localhost:3000/orders/add
Content-type: application/json

{
    "name": "Hugo",
    "orderNumber": 2131,
    "paymentMethod": "Card",
    "email": "perp@mail.com",
    "phone": 2,
    "adress": "bordet 12 Ystad",
    //"cart": ,
    "isSent": false,
    "delivery": "Korp 20230914",
    "isDeleted": false
}

###


// === update order ===

PUT http://localhost:3000/orders/update/65005f44a967199ae1e278f7
Content-Type: application/json

{
    "isSent": true
}

###


// === soft-delete order ===

PUT http://localhost:3000/orders/delete/65005f44a967199ae1e278f7
Content-Type: application/json

{
    "isDeleted": true
}

###