// === alla produkter ===

GET http://localhost:3000/orders


###

// === add product ===

POST http://localhost:3000/orders/add
Content-type: application/json

{
    "name": "Phillipe",
    "orderNumber": 1,
    "paymentMethod": "Card",
    "email": "merp@mail.com",
    "phone": 2,
    "adress": "hyddan 12 Mariestad",
    "cart": [{
        "productId": "65005ccb511d2f8d52a25be9",
        "quantity": 2
    }],
    "isSent": false,
    "delivery": "Flaskpost 20230914"
}

###


// === update product ===

PUT http://localhost:3000/orders/update/650047050df9a59622e40eb3
Content-Type: application/json

{
    "isSent": true
}

###