// === alla produkter ===

GET http://localhost:3000/products


###

// === product by id =====

GET http://localhost:3000/products/650022232add00d8c0438d19


###

// === add product ===

POST http://localhost:3000/products/add
Content-type: application/json

{
    "name": "AnotherBigBoi",
    "image": "https://images.unsplash.com/photo-1557431177-36141475c676?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    "shortDesc": "HoHo?",
    "description": "Bambozeld u got again",
    "price": 1000002,
    "quantity": 2,
    "isAvailable": true,
    "isDeleted": false
}

###

// === soft-delete product ==

PUT http://localhost:3000/products/delete/650022232add00d8c0438d19
Content-Type: application/json

{
    "isDeleted": true
}

###

// === update product ===

PUT http://localhost:3000/products/update/650348a7a59e2c177a4a637c
Content-Type: application/json

{
    "name": "apple",
    "image": "https://unsplash.com/photos/3fjyk4CLfvA",
    "shortDesc": "POTATO!",
    "description": "POTATO!POTATO!POTATO!",
    "price": 1300,
    "quantity": 12,
    "isAvailable": true,
    "isDeleted": false
}

###

// === update availability ==

PUT http://localhost:3000/products/available/65005ccb511d2f8d52a25be9
Content-Type: application/json

{
    "isAvailable": false
}

###